import Header1 from "./_components/header";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body >
        <Header1/>
        <div className="layout-js pt-[50px] h-svh w-full max-w-[500px] mx-auto">
            {children}
        </div>
      </body>
    </html>
  );
}
